resolver 127.0.0.11 valid=10s ipv6=off;

limit_req_zone $binary_remote_addr zone=api_limit:10m rate=120r/m;
limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=10r/m;

upstream frontend_upstream {
    zone frontend_upstream 64k;
    server frontend:80 resolve;
    keepalive 32;
}

upstream backend_upstream {
    zone backend_upstream 64k;
    server backend:8080 resolve;
    keepalive 32;
}

server {
    listen 443 ssl;
    http2 on;
    server_name _;

    ssl_certificate /etc/nginx/certs/tic-tac-toe.crt;
    ssl_certificate_key /etc/nginx/certs/tic-tac-toe.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    include /etc/nginx/conf.d/routes/system.conf;
    include /etc/nginx/conf.d/routes/api.conf;
    include /etc/nginx/conf.d/routes/frontend.conf;
}
