location = /tic-tac-toe/games {
    limit_req zone=api_limit burst=20 nodelay;
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/games;
}

location ^~ /tic-tac-toe/games/ {
    limit_req zone=api_limit burst=20 nodelay;
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/games/;
}

location = /tic-tac-toe/users {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/users;
}

location ^~ /tic-tac-toe/users/ {
    limit_req zone=api_limit burst=20 nodelay;
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/users/;
}

location = /tic-tac-toe/auth {
    limit_req zone=auth_limit burst=5 nodelay;
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/auth;
}

location ^~ /tic-tac-toe/auth/ {
    limit_req zone=auth_limit burst=5 nodelay;
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/auth/;
}
