location = /healthz {
    add_header Content-Type text/plain;
    return 200 "ok\n";
}

location = / {
    return 308 /tic-tac-toe/;
}

location = /tic-tac-toe {
    return 308 /tic-tac-toe/;
}

location = /tic-tac-toe/healthz {
    add_header Content-Type text/plain;
    return 200 "ok\n";
}

location = /tic-tac-toe/frontend-healthz {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://frontend_upstream/healthz;
}

location = /tic-tac-toe/readyz {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/readyz;
}

location = /tic-tac-toe/swagger {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/swagger;
}

location = /tic-tac-toe/openapi.yaml {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/openapi.yaml;
}

location = /tic-tac-toe/swagger/doc.json {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/swagger/doc.json;
}

location = /tic-tac-toe/metrics {
    include /etc/nginx/conf.d/proxy_headers.conf;
    proxy_pass http://backend_upstream/metrics;
}
